import type {Metadata, Viewport} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import React from "react";

import {Header} from "@/app/components/main/Header";
import {Footer} from "@/app/components/main/Footer";
import {Sidebar} from "@/app/components/main/Sidebar";


const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Blog",
    description: "Generated by create next app",
};

export const viewport: Viewport = {
    themeColor: 'black',
    initialScale: 1,

}

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
                  integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
                  crossOrigin="anonymous"/>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
                    integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
                    crossOrigin="anonymous"></script>
            <script src="https://kit.fontawesome.com/efab6387bf.js" crossOrigin="anonymous"></script>
            <title>Blog</title>
        </head>
        <body className={inter.className}>
        <Header/>
        <main className="container-fluid bg-light min-vh-100">
            <div className="row">
                <div className="col-md-2 min-vh-100 mt-3 p-0 bg-white">
                    <Sidebar/>
                </div>
                <div className="col-md-10">
                    <section className="pb-5">
                        {children}
                    </section>
                </div>
            </div>
        </main>
        <Footer/>


        </body>
        </html>
    );
}
